hash-format = "sha256"

[[files]]
file = "CustomSkinLoader/CustomSkinLoader.json"
hash = "81475fb1b0314b17387bf5784f518f68ac843e0a3e936f637e048ba4153fb598"

[[files]]
file = "GamersReforged.png"
hash = "3caa492e3139d94b59eb21328c925c1029f15031719eb3950480290046afc9a4"

[[files]]
file = "config/ProjectE/client.toml"
hash = "37ddcfd8b8273e43c1cac83519faeb927a3adbba4352c7e130443bd4e3970fb9"

[[files]]
file = "config/bettermodsbutton-client.toml"
hash = "c3a94737d9bc1aa90830993920154b4c0feb19e65016bbd8dd58d909c24d0b72"

[[files]]
file = "config/create-client.toml"
hash = "cea97aa18991892d849acb9e64fe2a8391cffdf505b4344bc57c9cb195e3fd6c"

[[files]]
file = "config/extrabotany-client.toml"
hash = "42f279ec22ab7a16a2118549b22def70435d9209c98cc356948976b7062861b1"

[[files]]
file = "config/iceandfire-client.toml"
hash = "7edba4ec08ab1f9c0b492f6d181dacfc54ffcfba7efdd50f359302561363e6d8"

[[files]]
file = "config/itemphysic-client.json"
hash = "a5b3f024fb5c7d5637f488e0f0ea7f50ce86e36ca5247273976a70c2aafe0c8c"

[[files]]
file = "config/packmenu.cfg"
hash = "1d2ce1b5d6616b109bfbfaff640d3542832bd67483682f762b58926de9003a31"

[[files]]
file = "config/performant-common.toml"
hash = "36542e5af5ff85a538e0ea7595bfc01dca0efb07c4720170ec0157f993b9238f"

[[files]]
file = "config/quark-common.toml"
hash = "7563c8a5416a83d0ec119bdcf356cac48bb04a27a73e0fb2c4d514bd7f1081a8"

[[files]]
file = "config/tips-client.toml"
hash = "4d9382486d8737356e1175a02008999e0a46216307053570c11ef00064c45911"

[[files]]
file = "config/vampirism-common.toml"
hash = "5cf69bb6b5f5490a9996b552b058e7f348a717cf69e39f7c6357bbe2969dfb16"

[[files]]
file = "defaultconfigs/fpsreducer/fpsreducer-client.toml"
hash = "718bff5ecc613b7367feab47713120b229f10afa2750e6f52c4e37cdc9b6c97e"

[[files]]
file = "mods/advanced-chimneys.toml"
hash = "7e65e90c62497c218b81b71fc1f0786530db1d0964e22cd729ddfe29717668c2"
metafile = true

[[files]]
file = "mods/advanced-peripherals.toml"
hash = "6a57f91ba9e17240dc404d6d75b0f69a661c0dd1509383e9a5f352aeeaf43154"
metafile = true

[[files]]
file = "mods/advancement-plaques.toml"
hash = "6450e406f87498557e43f1b713edfa9f5cb97cda0dd43427d8df9bba4edd0489"
metafile = true

[[files]]
file = "mods/ai-improvements.toml"
hash = "78a2974be4ca1553dc4d339f6ebe6eee69e3113389b2fea2667a3678cf207c29"
metafile = true

[[files]]
file = "mods/antique-atlas.toml"
hash = "369b4bf185fdb737c0f43689a5453a48892d5e3a8ec7b82364dfe20fb4462666"
metafile = true

[[files]]
file = "mods/apotheosis.toml"
hash = "8f57f44a5f10215e93d6ef1789c65c3f774cf92d65f0280ba715989015160e57"
metafile = true

[[files]]
file = "mods/applied-energistics-2.toml"
hash = "983beffdfcf8b3bb0d5e4e8e7fb4925e7a54e24f044754d86060c061d7ed7032"
metafile = true

[[files]]
file = "mods/aquaculture.toml"
hash = "86d2ccabf5b6e5eb9011d882f75a1f66f04321b5dad3d20f74f9d21f6f604c30"
metafile = true

[[files]]
file = "mods/atum.toml"
hash = "c459fc6ed805e048072e5d383ffcfb6124c009a6e4d9bbab1ccdd634c79afdf7"
metafile = true

[[files]]
file = "mods/autoreglib.toml"
hash = "ba9514853e9c9dd3392446dce8dcc4c63ea243bed64c4291b49003b1df12b1b5"
metafile = true

[[files]]
file = "mods/better-mods-button.toml"
hash = "66b182faeadb22e44f26d01174ca4a64c5c6cf6cdeb663e67fe77c871f2514d2"
metafile = true

[[files]]
file = "mods/biomes-o-plenty.toml"
hash = "f01dba9cfed356f4cd35db04cff27e6238b28864af71f2e263a89060904dd9b6"
metafile = true

[[files]]
file = "mods/bookshelf.toml"
hash = "d67a3fd5f36f1566488ecab3b9230b15a18ae6041e2835a74b0ce4deb41d920e"
metafile = true

[[files]]
file = "mods/botania.toml"
hash = "1848c9853eb4290c6324f87ef9a97ff22a81ed7aef2a8f43b2769f851f53080e"
metafile = true

[[files]]
file = "mods/camera-overhaul-forge.toml"
hash = "d5f658099c192e8b1d9c7c0075644eba4871efda2100669f83a92e05fe96cb09"
metafile = true

[[files]]
file = "mods/catalogue.toml"
hash = "2487a10f0033f5f950b9a61942148d24fa3482eecba22a3f6fb353b8df5db1d7"
metafile = true

[[files]]
file = "mods/cc-tweaked.toml"
hash = "47b141c0f26803082aaff85c7545ce421505e4a687c7128c9f2fbd6c33da4938"
metafile = true

[[files]]
file = "mods/chunk-loaders.toml"
hash = "74f88515446e96f2ad7c0eeaaec74864a5bd5bf39ce227034ee3966d955a1aca"
metafile = true

[[files]]
file = "mods/citadel.toml"
hash = "e1c06b486de303676e9b35336db571f1045e8af8612e1351868295ca5ec1d727"
metafile = true

[[files]]
file = "mods/client-tweaks.toml"
hash = "3cd69fc6abbe2eee23919e365cc9e569f06d8cd758bbd05557962729f5371efd"
metafile = true

[[files]]
file = "mods/cloth-config.toml"
hash = "482c9c925311a0b0fd473cb563e955d68798fff6313973abfbd1d4d1db682711"
metafile = true

[[files]]
file = "mods/cofh-core.toml"
hash = "6fc24b1360d3fa602b18ab310320eacafb8bcbf2f623e1a94273f0bb7166ab56"
metafile = true

[[files]]
file = "mods/compact-machines.toml"
hash = "c22694d13861c2bb7177d842d73c7b25a380b086d9f88afc6ae28caadad7076f"
metafile = true

[[files]]
file = "mods/configured.toml"
hash = "26f7735c9d09f929d47f24122766b2bcbc191b6f9777b81237e9dcb4f4a9ebf9"
metafile = true

[[files]]
file = "mods/corail-tombstone.toml"
hash = "a9d3331246dea7821b397c21bc5956e50a90ef491d084ea1b52062621e90cd46"
metafile = true

[[files]]
file = "mods/create.toml"
hash = "5343506f8c1acb3502f94ef336e6af0d21519f90f39405b0c2789f70c2ffd2c5"
metafile = true

[[files]]
file = "mods/creativecore.toml"
hash = "e9bcbdc7ea8718d5c89315770f769834e897b68285745a7ea1eaf389476ea8be"
metafile = true

[[files]]
file = "mods/curios.toml"
hash = "06d7a52c2514494ba32779a7b31418a0f702a057780013590594639da581ed37"
metafile = true

[[files]]
file = "mods/customskinloader.toml"
hash = "6c643015d3a4b8810e434a936088c3b0482a4ff8292a39630be680f54a3c1030"
metafile = true

[[files]]
file = "mods/cyclic.toml"
hash = "d9d7fd1e322d554d31a39922d8f675e3ba197df7c58353a766ff455d1a8f764a"
metafile = true

[[files]]
file = "mods/cyclops-core.toml"
hash = "53bb90dd6a039ae924a4e796c3b5b1dc69f1941b9dc47fb05c88c3c75ed544ca"
metafile = true

[[files]]
file = "mods/dynamic-surroundings.toml"
hash = "4519399d9f2958841a3299d6df5ea042bb395c9ce037a057526b0c56c16283c9"
metafile = true

[[files]]
file = "mods/dynamic-view.toml"
hash = "1dc058d27b1cbc50f4b0266671992469e7be458403562dcf032162a578ee5631"
metafile = true

[[files]]
file = "mods/enigmatic-legacy.toml"
hash = "4f2e19367edb789d80b021ed16cf9d81275d5acff84f886937f0257f42f2a4ae"
metafile = true

[[files]]
file = "mods/evilcraft.toml"
hash = "42c1ad5838e7bbfbd0a35483847448cd13aa085bb7c819d3708e6a5514b784f5"
metafile = true

[[files]]
file = "mods/extrabotany.toml"
hash = "3407b78fc902649c71ad444ebb084abdff8cc2c79c0dacef0035302bba22493c"
metafile = true

[[files]]
file = "mods/farmers-delight.toml"
hash = "bfcdb900465370be5e8f98bcbca1137ba6ebaffc27b3577823153c12d0394a20"
metafile = true

[[files]]
file = "mods/fast-leaf-decay.toml"
hash = "bda906a44e96526d08e68b8c504e6a31a691bd95ff8ba186f0887bfc325bac22"
metafile = true

[[files]]
file = "mods/fastsuite.toml"
hash = "35621f8d7144d6f09eec2be534c9fff2b238f9703d9428dc5076446e8f539ae3"
metafile = true

[[files]]
file = "mods/ferritecore.toml"
hash = "305affb1cff160ec5cd4f1c23192259985870e10eb94ce52cb54afba63f7c6b4"
metafile = true

[[files]]
file = "mods/flywheel.toml"
hash = "3a332123aec6bda27daffae9f04ccf3d0d71baa4cf3cea0ce2d5823ac9e3d432"
metafile = true

[[files]]
file = "mods/forgeendertech.toml"
hash = "e8ff915c7f18dbab9323c080c34275fccaf761f5de5ea86f9ee27e7b9b20ca32"
metafile = true

[[files]]
file = "mods/fps-reducer.toml"
hash = "3826f00cc0c78a240ba551112bea34f59cc64ce067b8815c403a37188b0a85fc"
metafile = true

[[files]]
file = "mods/ftb-backups-forge.toml"
hash = "c5d597667ea5fed34e18927c576f36d907d3c6bc7b81d3cd5b1676f30f7217e1"
metafile = true

[[files]]
file = "mods/geckolib.toml"
hash = "f0cf3024165ad4253419e47178ea022b78ca44b1e92bdfcd8f93a0b16862d4e6"
metafile = true

[[files]]
file = "mods/gokistats.toml"
hash = "2aa4bb94e723026ed75f4cc0343f9abbfc61012719661992024476e097668de1"
metafile = true

[[files]]
file = "mods/guide-api-village-and-pillage.toml"
hash = "7cfcc9731b7d9e2ff44adbdb9e2b8d8754d119433d0f5ed9b621f7c6096e5723"
metafile = true

[[files]]
file = "mods/hwyla.toml"
hash = "a12a7e2eeaea2e2bb75d072bd80e57bb30146c54f46eada797edd567f2c54931"
metafile = true

[[files]]
file = "mods/ice-and-fire-dragons.toml"
hash = "22554998e0c1210389e5dd2a2e805f874435503c431ccbe0b8f4af9b61f5c411"
metafile = true

[[files]]
file = "mods/iceberg.toml"
hash = "f5901e29a05694a278b4714921db82363393fa13904e5e958ea894b1a22f6981"
metafile = true

[[files]]
file = "mods/itemphysic.toml"
hash = "ea75886dddd5865f65f0861c5ece905e324f8e3f96f24946bb1f70046bd0f789"
metafile = true

[[files]]
file = "mods/jaopca.toml"
hash = "4e34ccf8624fd586e673791087f6335281edfe799e452cbd2d39a016d6d33853"
metafile = true

[[files]]
file = "mods/jei.toml"
hash = "3f8803ed3daea9508f4617adc6435597f18df2d5ba8878951ebbbbdc841d9e61"
metafile = true

[[files]]
file = "mods/kiwi.toml"
hash = "13f10c0ef963874f79fe2213a3b63245a710a3cf9953d0a4009cdd53529fc48d"
metafile = true

[[files]]
file = "mods/lazy-dfu-forge.toml"
hash = "96aa94af84d9d63fb8d9b27317f95a00721bc3144d2461faa7a456b4e16ad188"
metafile = true

[[files]]
file = "mods/mantle.toml"
hash = "11d0f742d0bfc55782aac3b91b572972f57b0d3b5799759fcb57198d2faa8bc4"
metafile = true

[[files]]
file = "mods/materialis.toml"
hash = "7cd9f44123792b551846cc62ccea3604023926cbb273144a6e58e583dde37272"
metafile = true

[[files]]
file = "mods/mekanism-additions.toml"
hash = "0a3ab08ee13a00db218f123f936d5f06499bcd61e0cfa5ab88ddbe53b37a57d8"
metafile = true

[[files]]
file = "mods/mekanism-generators.toml"
hash = "edf599390183a6ddd9c15646a04f69c7b2a6980d564431e1042271fc24c866b4"
metafile = true

[[files]]
file = "mods/mekanism-tools.toml"
hash = "1c722af6f443c41d4e8f9aed9a400545c4bc85ba68793b55bf9fa709e23b3f0a"
metafile = true

[[files]]
file = "mods/mekanism.toml"
hash = "2d296dcf757625fbb4deb60b00fb9fb7b0d9a87a0a682a9ae760dcfd8460c568"
metafile = true

[[files]]
file = "mods/minecolonies.toml"
hash = "c4a39dd8be2f24da89d0006fd76590d0f65c454b91f9751849747f627018bf9c"
metafile = true

[[files]]
file = "mods/more-mekanism-processing.toml"
hash = "be59d6a29eeb55ac401033ae8a8c67ebbc116fbc2944437e3c4a165f11a95d78"
metafile = true

[[files]]
file = "mods/moving-elevators.toml"
hash = "31482a70bd4c81371716dbd17d680dc1c5f31c2e394bc575ace8b8948a2ea006"
metafile = true

[[files]]
file = "mods/mrcrayfish-furniture-mod.toml"
hash = "7035dd99730c84b68c024c050ee08f15e8a107c11d3fdf3d8abe061adf8d08d9"
metafile = true

[[files]]
file = "mods/oculus.toml"
hash = "9d571ef45ecb002b79837ad852100fb6558fe78a9cff1a083a885828ceff5240"
metafile = true

[[files]]
file = "mods/packmenu.toml"
hash = "c928a7e03f7d714e6f025648f50a60068f663097465c8bffa2b58eb671ba0821"
metafile = true

[[files]]
file = "mods/patchouli.toml"
hash = "4096fe53f38b3a3132f6008c6e06108896baf662196c90f124ffc9054021a0dd"
metafile = true

[[files]]
file = "mods/performant.toml"
hash = "36e7e4332d001e5a563eccdf95ce0be4d481bf18ce44e458802618b382dd9266"
metafile = true

[[files]]
file = "mods/placebo.toml"
hash = "52a3a8c8c810785d1bb8d32fb95bbb9a3dc2d88f053e185396a21c83eefd3396"
metafile = true

[[files]]
file = "mods/pollution-of-the-realms.toml"
hash = "845a5cdf144dc57fcb9d60cc24c506e17bfc8250201259f126927bd09f71a0df"
metafile = true

[[files]]
file = "mods/project-mmo.toml"
hash = "76416758aead17fc71e29b5146abf8610ed10e88ba0d0a93730fd2dad39d9a41"
metafile = true

[[files]]
file = "mods/projecte.toml"
hash = "41d27427c38f15b4d513c744a295905dd25866977763b0f85866b76dc149d9bd"
metafile = true

[[files]]
file = "mods/quark.toml"
hash = "ee49ae892b8d1483172b2132f30b96a3ba45d2d46ba51a2113e0aee3eb90c909"
metafile = true

[[files]]
file = "mods/rats-ratlantis.toml"
hash = "d0bea0328c47361da17b2560422fee8e415d4dfe49c5b8f0f48f6d56795045ad"
metafile = true

[[files]]
file = "mods/rats.toml"
hash = "405a94a3eb8885f355632b7978cad63b32b5e14bd1ea33f252b379442a199dda"
metafile = true

[[files]]
file = "mods/relics-mod.toml"
hash = "127e37034323a03c550ba88ca4916660375aafdffe6df398412afee56cb5e1d2"
metafile = true

[[files]]
file = "mods/rubidium.toml"
hash = "97d555cd201bd1bd034af4e92419e8532cae25fd2435a6181dcdbf6cf3d8a44a"
metafile = true

[[files]]
file = "mods/screenshot-to-clipboard.toml"
hash = "3255624848075ce112318b1370d0895efd93d88c9f76198e8d140e5213afd627"
metafile = true

[[files]]
file = "mods/seamless-loading-screen-forge.toml"
hash = "a6b7252a8df648ff93b76700536a74e5b0ac8e47ace10f4fd607db76951dc250"
metafile = true

[[files]]
file = "mods/shutup-experimental-settings.toml"
hash = "8c780b20ce184c219bc47a96fbbc561c2ac9ca469f1b28b96cab535b7b8f8f0e"
metafile = true

[[files]]
file = "mods/smooth-boot-forge.toml"
hash = "8d9834d190bc83e098642d24e6e8c6b7c46b73bd85b4f5cb50e6dc5503780c7a"
metafile = true

[[files]]
file = "mods/snow-real-magic.toml"
hash = "5b3ddd491e41e5cafc05d7f5491473765eec5076b863ca538825658642fae48f"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks.toml"
hash = "700dd7952f9de841729dbdb216c22bca853a17b0ee02588524b230193df2e8e3"
metafile = true

[[files]]
file = "mods/spartan-shields.toml"
hash = "110d1c6e2574a1ef1a62c7d4d20dff33e806a095f79200aa21424199c9db26ed"
metafile = true

[[files]]
file = "mods/starlight-x-create.toml"
hash = "78ca93c122fb037c28dfaf7d7255a8981bc789de47811e98394514b6aba2780d"
metafile = true

[[files]]
file = "mods/structurize.toml"
hash = "2cc9b3c970c8b1a468e2389d0d491b7c91c7496fee433e57d52d275b423a7de6"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.toml"
hash = "2db7b8faeb52b79c979ecf5500785e392c6b234ccfab2474b119b5957903ff23"
metafile = true

[[files]]
file = "mods/supermartijn642s-core-lib.toml"
hash = "df9993fa664757a9f5eb1a85a3af2e3fc999c86c6494bca24388c5e772ea0891"
metafile = true

[[files]]
file = "mods/the-legend-of-herobrine.toml"
hash = "fdff04418e2295c70a35a84561f96be8674bf58e3ca3adc28ad7581189a009a1"
metafile = true

[[files]]
file = "mods/the-twilight-forest.toml"
hash = "1b10c25012b1136ee172cbaa2c1db9c01777654b5d4037aba7ec71c2209265e5"
metafile = true

[[files]]
file = "mods/tinkers-construct.toml"
hash = "044d74230f70d2b13dff848bb4c9e9e6ddf1cc3333c7588dd7e10edb79d9fd5a"
metafile = true

[[files]]
file = "mods/tinkers-delight.toml"
hash = "c99a8dfc4547751ba5066f59bb6d502133183cc15b480e0b596000444b90fa5a"
metafile = true

[[files]]
file = "mods/tinkers-planner.toml"
hash = "7a0164c327f5a889752ea202f30b789c73a2d08537cc1cbc23d4e26e901cda79"
metafile = true

[[files]]
file = "mods/tinkers-rapier.toml"
hash = "1a3b17cacc596f98224e722b81f08219c29f76a5ae5f9207a146b5d8964a7b50"
metafile = true

[[files]]
file = "mods/tips.toml"
hash = "73083b71a28bcb2b4352b440ad48d7b1300df9b01486beb3f5f57bbd297c1338"
metafile = true

[[files]]
file = "mods/valhelsia-core.toml"
hash = "2cb163872a1e3709cd87ecb73ac432205d52bb4fa558e8437d147b41872c6eed"
metafile = true

[[files]]
file = "mods/valhelsia-structures.toml"
hash = "953e50e1e8bd9228d2f8dd0e1c0c0752ce12e383f5e66bf1f6bbdd8766b73b20"
metafile = true

[[files]]
file = "mods/vampirism-become-a-vampire.toml"
hash = "e023645c1ae464423ed7008f6c30900cd07d0bd77f87a14d9d7e4a8104d3c8c3"
metafile = true

[[files]]
file = "mods/vampirism-integrations.toml"
hash = "95293aec91f5c247270830444abc413fd4f0c463ee3588b5c84e9ddc313d992a"
metafile = true

[[files]]
file = "mods/wawla.toml"
hash = "565c94a91f4b8d7682320a161e5e34e92f618add4af32f74b36b7162133907fc"
metafile = true

[[files]]
file = "mods/werewolves-become-a-beast.toml"
hash = "1f3d5e6a22ee115c8096f513d480be5ddbdacac255379113090c6660a8e64436"
metafile = true

[[files]]
file = "mods/wireless-chargers.toml"
hash = "352c5c32ca2f92e906cfd9803efe9ad11cceea1ed552a7792c9eb0ed1bd39cae"
metafile = true

[[files]]
file = "pack.ico"
hash = "7359b1780eb1ecdc21b5566b8302f358f822d46ff57c3d8d2fa258b90d4656ef"

[[files]]
file = "packmenu/resources/assets/adpother/lang/ru_ru.json"
hash = "35caf1f1a1990c4bd103b95deadd2263d68a4a2206558f453df63d6dfda55a19"

[[files]]
file = "packmenu/resources/assets/adpother/lang/uk_ua.json"
hash = "1dc0b72e07c8dce71e8e8a5857ac8a8eff83d4f46d0d28e4d7641e4b560bb3a1"

[[files]]
file = "packmenu/resources/assets/compactmachines/lang/ru_ru.json"
hash = "77abd9408e1b03b34f36a7d0ca662a9844cbb44d81bba6d1ca6a07bb21723108"

[[files]]
file = "packmenu/resources/assets/jaopca/lang/ru_ru.json"
hash = "e764f7b0487f78edd85c37d2435d3fcaa6652823647fe5c0ffbfa3f0147d5179"

[[files]]
file = "packmenu/resources/assets/moremekanismprocessing/lang/ru_ru.json"
hash = "ab4ca0b3def42790d0dde4d49e5af5851c0ad2054d6463ff8b268617bc517632"

[[files]]
file = "packmenu/resources/assets/packmenu/buttons/accessibility.json"
hash = "88f8547629519b1cc8724952ef2b7eec805c2eebb7530de7dd7998d4be2a7bcf"

[[files]]
file = "packmenu/resources/assets/packmenu/buttons/language.json"
hash = "2c31db4e6877cb80f8fb65b7bb88201e8fe290b87776f8ca7c7334bcea000a08"

[[files]]
file = "packmenu/resources/assets/packmenu/buttons/mods.json"
hash = "860771e23ae882c93f597198e493237eaa193c73deb699adb38ea2baccb78a15"

[[files]]
file = "packmenu/resources/assets/packmenu/buttons/multiplayer.json"
hash = "e1ae3e0c986cd28e777cdcc59135cc54423a0bb8f253c361f0f4d8d8d946b2ce"

[[files]]
file = "packmenu/resources/assets/packmenu/buttons/options.json"
hash = "cf0ac731f880d5378f19c44c31de15fc4a71b9a457389316841badd76aa14170"

[[files]]
file = "packmenu/resources/assets/packmenu/buttons/quit.json"
hash = "b8b8a955950b28a78f7f4783231693be293a3eb1537412c42e9b65e0bfe40200"

[[files]]
file = "packmenu/resources/assets/packmenu/buttons/singleplayer.json"
hash = "de47792809583e07ae8b3f24b0cf2d906f8e03813f33a234744dfdf34c1d41d1"

[[files]]
file = "packmenu/resources/assets/packmenu/lang/en_us.json"
hash = "d771e08bccbe2a20a438cac58d3d87318a31baedb0244ad9b53ade9035dcf82f"

[[files]]
file = "packmenu/resources/assets/packmenu/textures/gui/background.png"
hash = "f32b135e685eadb8c79837fbf6d41da25b8a495b4b6c762abca7cc19fbe0b779"

[[files]]
file = "packmenu/resources/assets/packmenu/textures/gui/logo.png"
hash = "1feb9a1de37759088b41fb1ef6a086f50ab928e68882039590dcea4fc8b153ae"

[[files]]
file = "packmenu/resources/pack.mcmeta"
hash = "18c978e312f381a09350f2c1cd61e244419a77592e8b0bc973a6c31224c895f0"

[[files]]
file = "packmenu/resources/pack.png"
hash = "3caa492e3139d94b59eb21328c925c1029f15031719eb3950480290046afc9a4"

[[files]]
file = "resourcepacks/default-dark-mode.toml"
hash = "bca1bf904fbf11819b35c834eecaf033cabd06eb2005e36b198ad7dfa654bea0"
metafile = true
