name = "Wireless Chargers"
filename = "wirelesschargers-1.0.6-forge-mc1.16.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3774/40/wirelesschargers-1.0.6-forge-mc1.16.jar"
hash-format = "sha1"
hash = "8322448b7bf6cc73fb76ff2326b0701c2d9ab71f"

[update]
[update.curseforge]
file-id = 3774040
project-id = 510656
